### ISSUE TITLE
Game crash when attempting to load with DustClouds weather

### ISSUE THREAD

**Issue by CoatUlta** [Toliann/EchoReach#1]
When attempting to load the moon with the "DustClouds" weather, the game crashes. I couldn't find any errors in console. Should be easy to reproduce (unless it's a hardware or dependency issue).

**Comment by Kajot-dev** [comment]
100% reproducible with relatively new nvidia cards on both windows and linux with wine.

Error looks like this:
```
ERROR: Shader Hidden/HDRP/TerrainLit_Basemap shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
```

Dumps, logs and stack traces:
[Crash_windows.zip](https://github.com/Toliann/EchoReach/files/14469665/Crash_windows.zip)
[Crash_linux.zip](https://github.com/Toliann/EchoReach/files/14469667/Crash_linux.zip)
