### ISSUE TITLE
Dungeon and Backrooms mod spawn at the same place (see attached imgur picture)

### ISSUE THREAD

**Issue by SirPrepu** [Toliann/EchoReach#3]
Hi there.

I was play testing a mod pack I made to play with friends and I've encountered this weird behaviour in this specific map:
https://imgur.com/a/3cbFgMn

It seems like the spawn point of the dungeon and the Backrooms mod share the same place in the map or something similar.

This happens only in this map, I've also played Echelon but there is all fine.

**Comment by Toliann** [comment]
Check the latest version
